version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/flask-app
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
    - location: scripts/start_server.sh
      timeout: 300
    - command: chmod +x scripts/application_stop.sh
    - command: chmod +x scripts/after_install.sh
    - command: chmod +x scripts/start_server.sh
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
