version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Installing pip dependencies..."
      - pip install -r requirements.txt
      - chmod +x scripts/application_stop.sh
      - chmod +x scripts/after_install.sh
      - chmod +x scripts/start_server.sh
  build:
    commands:
      - echo "Build complete."
artifacts:
  files:
    - '**/*'
  base-directory: /
